version: "3.7"

services:
  das-mongo:
    image: "mongo:6.0.5"
    container_name: das-mongodb
    restart: always
    volumes:
        - "./db/data/db-files:/data/db"
        - "./db/init/:/docker-entrypoint-initdb.d/"

    ports:
      - "27017:27017"


  das-ui:
    container_name: das-ui
    restart: on-failure

    build:
      context: .
      dockerfile: ./apps/ui/das-ui/Dockerfile

    ports:
      - "8080:80"


  das-api:
    container_name: das-api
    restart: always

    build:
      context: .
      dockerfile: ./apps/webapi/das-api/Dockerfile

    volumes:
      - .:/app

    environment:
      - NODE_ENV="development"
      - APP_PORT=3000
      - APP_NAME="Dashboard Starter Data"
      - API_PREFIX=das-api
      - APP_FALLBACK_LANGUAGE=en
      - APP_HEADER_LANGUAGE=x-custom-lang
      - MONGO_URI=mongodb://das-mongo:27017
      - MONGO_DB_NAME=das


    command: yarn start-api

    ports:
      - "3000:3000"
      - "8081:8081" # for socket.io events gateway
      - "9230:9229"

    depends_on: [das-mongo]


networks:
  das-network:
    name: das-network
    driver: bridge
