version: "3.7"

services:
  das_mongo:
    image: "mongo:6.0.5"
    container_name: das_mongodb
    restart: always
    volumes:
        - "./db/data/db-files:/data/db"
        - "./db/init/:/docker-entrypoint-initdb.d/"

    ports:
      - "27017:27017"


  das_ui:
    container_name: das_ui
    restart: on-failure

    build:
      context: .
      dockerfile: ./apps/ui/das-ui/Dockerfile

    ports:
      - "8080:80"


  das_api:
    container_name: das_api
    restart: always

    build:
      context: .
      dockerfile: ./apps/webapi/das-api/Dockerfile

    volumes:
      - .:/app

    environment:
      - NODE_ENV="development"
      - APP_PORT=3000
      - APP_NAME="Dashboard Starter Data"
      - API_PREFIX=das-api
      - APP_FALLBACK_LANGUAGE=en
      - APP_HEADER_LANGUAGE=x-custom-lang
      - FRONTEND_DOMAIN=http://localhost:3000
      - BACKEND_DOMAIN=http://localhost:3000
      - MONGO_URI=mongodb://das_mongo:27017
      - MONGO_DB_NAME=das_data

    command: yarn start-api

    ports:
      - "3000:3000"
      - "9230:9229"

    depends_on: [das_mongo]


  das_graphql:
    container_name: das_graphql
    restart: always

    build:
      context: .
      dockerfile: ./apps/webapi/graphql/Dockerfile


    volumes:
      - .:/app

    command: yarn start-graphql

    ports:
      - "3008:3008"
      - "9238:9229"

